name: Looping over values in Github Actions

on:
  push:

jobs:
  file-loopover:
    name: Loopover through pattern matching files
    runs-on: ubuntu-latest
    steps:
      - name: Echo values from ENV
        run: |
          files=$(find -name '*.md' -print)
          for file in $files; do echo $file; done
