# Build cargo repository for all platforms

name: Build

on:
  push:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Build Aries binary
        run: |
          git clone https://github.com/plaans/aries.git --branch grpc-server
          mkdir -p bins
          cd aries
          cargo build --release
          cp target/release/up-server ../bins/aries-linux-amd64
          tree -L 2 ..

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update aries binary for linux-amd64
          commit_options: '--no-verify'
          commit_user_name: github actions
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

          file_pattern: 'bins/*'' # Commit all files in the `bins` directory