# Build cargo repository for all platforms

name: Aries Compile CI

on:
  push:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04
    name: Build Aries - ubuntu20.04-amd64

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Clone Aries and Build
        run: |
          git clone https://github.com/plaans/aries.git --branch master
          cd aries
          cargo build --release
          # Add CI Tests for aries
          sudo apt-get install python3
          python3 ci/grpc.py

      - name: Upload Aries binary
        run: |
          cp target/release/up-server ../up_aries/bins/aries_linux_amd64
          cd ..
          strip up_aries/bins/aries-linux-amd64 # Strip the binary to reduce size
          bash .github/ci/github.sh amd64 linux

  build-linux-arm64:
    runs-on: ubuntu-latest
    name: Build Aries - ubuntu20.04-aarch64

    steps:
      - uses: actions/checkout@v3
      - name: Clone Aries
        run: |
          git clone https://github.com/plaans/aries.git --branch master
      - uses: uraimo/run-on-arch-action@v2
        name: Build Aries binary on ubuntu20.04 for aarch64
        id: build
        with:
          arch: aarch64
          distro: ubuntu20.04

          # githubToken: ${{ secrets.GITHUB_TOKEN }}

          setup: |
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get install -y libssl-dev libudev-dev pkg-config curl git
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo $HOME/.cargo/bin >> $GITHUB_PATH
            source $HOME/.cargo/env
              cd aries
            cargo build --release --bin up-server
            # Add CI Tests for aries
            sudo apt-get install python3
            python3 ci/grpc.py
            cp target/release/up-server ../up_aries/bins/aries_linux_aarch64

          dockerRunArgs: |
            --privileged --volume "${PWD}:/workdir" --workdir /workdir

          shell: /bin/sh
          run: |
            echo "Build Aries binary on ${{ matrix.distro }} for ${{ matrix.arch }}"

      - name: Upload Aries binary
        run: |
          strip up_aries/bins/aries-linux-aarch64 # Strip the binary to reduce size
          bash .github/ci/github.sh aarch64 linux

  build-macos:
    runs-on: macos-latest
    name: Build Aries - macos-latest-amd64

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Clone Aries and Build
        run: |
          git clone https://github.com/plaans/aries.git --branch master
          cd aries
          cargo build --release --bin up-server

          # Add CI Tests for aries
          brew install python@3.8
          python3 ci/grpc.py

      - name: Upload Aries binary
        run: |
          # Copy the binary to the bins folder
          cp target/release/up-server ../up_aries/bins/aries_macos_amd64
          cd ..
          strip up_aries/bins/aries_macos_amd64 # Strip the binary to reduce size

          # Upload the binary
          bash .github/ci/github.sh amd64 macos

  build-macos-arm64:
    runs-on: macos-arm64
    name: Build Aries - macos-arm64

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Clone Aries and Build
        run: |
          git clone https://github.com/plaans/aries.git --branch master
          cd aries
          cargo build --release --bin up-server

          # Add CI Tests for aries
          brew install python@3.8
          python3 ci/grpc.py

      - name: Upload Aries binary
        run: |
          # Copy the binary to the bins folder
          cp target/release/up-server ../up_aries/bins/aries_macos_aarch64
          cd ..
          strip up_aries/bins/aries_macos_aarch64 # Strip the binary to reduce size

          # Upload the binary
          bash .github/ci/github.sh aarch64 macos

  build-windows:
    runs-on: windows-latest
    name: Build Aries - windows-latest-amd64

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          override: true

      - name: Clone Aries and Build
        run: |
          git clone https://github.com/plaans/aries.git --branch master
          cd aries
          cargo build --release --bin up-server

      - name: Upload Aries binary
        run: |
          cp target/release/up-server.exe ../up_aries/bins/aries_windows_amd64.exe
          cd ..
          strip up_aries/bins/aries_windows_amd64.exe # Strip the binary to reduce size
          bash .github/ci/github.sh amd64 windows
